'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LevelsetResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Skrzynki.LevelsetResource", GetType(LevelsetResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 60
        '''*
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;111&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;131&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;101111&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;11120231&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;13025111&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;111121&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;131&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;111&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&a....
        '''</summary>
        Friend Shared ReadOnly Property LevelsetClassic() As String
            Get
                Return ResourceManager.GetString("LevelsetClassic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 60
        '''*
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;111111&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;1103051&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;1020201&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;1304031&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;1020201&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;1003011&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;111111&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        '''&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&....
        '''</summary>
        Friend Shared ReadOnly Property LevelsetXS() As String
            Get
                Return ResourceManager.GetString("LevelsetXS", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
