'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    'przez narzędzie, takie jak ResGen lub Visual Studio.
    'Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    'z opcją /str lub ponownie utwórz projekt VS.
    '''<summary>
    '''  Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LocalizableStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Skrzynki.LocalizableStrings", GetType(LocalizableStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        '''  przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Flawless victory: you managed to complete this levelset!.
        '''</summary>
        Friend Shared ReadOnly Property AlertAllLevelsSolved() As String
            Get
                Return ResourceManager.GetString("AlertAllLevelsSolved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu There is no such level.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelDoesNotExist() As String
            Get
                Return ResourceManager.GetString("AlertLevelDoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The level file could not be read..
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelFileUnreadable() As String
            Get
                Return ResourceManager.GetString("AlertLevelFileUnreadable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The levelset could not be loaded..
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelsetLoadFailure() As String
            Get
                Return ResourceManager.GetString("AlertLevelsetLoadFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Glorious!.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelSolved() As String
            Get
                Return ResourceManager.GetString("AlertLevelSolved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Some levels in this file were left out:.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelsSkipped() As String
            Get
                Return ResourceManager.GetString("AlertLevelsSkipped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu • not valid: {0}.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelsSkippedNotValidFormat() As String
            Get
                Return ResourceManager.GetString("AlertLevelsSkippedNotValidFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu • too large (over {0}×{0} squares): {1}.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelsSkippedTooLargeFormat() As String
            Get
                Return ResourceManager.GetString("AlertLevelsSkippedTooLargeFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The file holds no level that can be played..
        '''</summary>
        Friend Shared ReadOnly Property AlertNoPlayableLevels() As String
            Get
                Return ResourceManager.GetString("AlertNoPlayableLevels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The solution could not be saved to that location..
        '''</summary>
        Friend Shared ReadOnly Property AlertSolutionSaveFailure() As String
            Get
                Return ResourceManager.GetString("AlertSolutionSaveFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        '''</summary>
        Friend Shared ReadOnly Property ButtonCancel() As String
            Get
                Return ResourceManager.GetString("ButtonCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Next.
        '''</summary>
        Friend Shared ReadOnly Property ButtonNextLevel() As String
            Get
                Return ResourceManager.GetString("ButtonNextLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu OK.
        '''</summary>
        Friend Shared ReadOnly Property ButtonOK() As String
            Get
                Return ResourceManager.GetString("ButtonOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Repeat.
        '''</summary>
        Friend Shared ReadOnly Property ButtonRepeatLevel() As String
            Get
                Return ResourceManager.GetString("ButtonRepeatLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Save solution as....
        '''</summary>
        Friend Shared ReadOnly Property ButtonSaveSolution() As String
            Get
                Return ResourceManager.GetString("ButtonSaveSolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Start levelsets at the furthest level reached.
        '''</summary>
        Friend Shared ReadOnly Property CheckBoxBeginFromArrivedLevel() As String
            Get
                Return ResourceManager.GetString("CheckBoxBeginFromArrivedLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Skrzynki level files (*.box)|*.box|Sokoban levelsets (*.sok)|*.sok.
        '''</summary>
        Friend Shared ReadOnly Property DialogFileFilter() As String
            Get
                Return ResourceManager.GetString("DialogFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Open level file.
        '''</summary>
        Friend Shared ReadOnly Property DialogOpenLevelFile() As String
            Get
                Return ResourceManager.GetString("DialogOpenLevelFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Save solution.
        '''</summary>
        Friend Shared ReadOnly Property DialogSaveSolution() As String
            Get
                Return ResourceManager.GetString("DialogSaveSolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Select level:.
        '''</summary>
        Friend Shared ReadOnly Property DialogSelectLevel() As String
            Get
                Return ResourceManager.GetString("DialogSelectLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Solution files (*.lurd)|*.lurd|Text files (*.txt)|*.txt|All files (*.*)|*.*.
        '''</summary>
        Friend Shared ReadOnly Property DialogSolutionFileFilter() As String
            Get
                Return ResourceManager.GetString("DialogSolutionFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Boxes: Skrzynki.
        '''</summary>
        Friend Shared ReadOnly Property GameName() As String
            Get
                Return ResourceManager.GetString("GameName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu {0} ({1}): #{2}.
        '''</summary>
        Friend Shared ReadOnly Property GameTitleFormat() As String
            Get
                Return ResourceManager.GetString("GameTitleFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Reached level: {0}.
        '''</summary>
        Friend Shared ReadOnly Property LabelAchievedLevelFormat() As String
            Get
                Return ResourceManager.GetString("LabelAchievedLevelFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Levelset:.
        '''</summary>
        Friend Shared ReadOnly Property LabelLevelSet() As String
            Get
                Return ResourceManager.GetString("LabelLevelSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Level solved.
        '''</summary>
        Friend Shared ReadOnly Property LabelLevelSolvedTitle() As String
            Get
                Return ResourceManager.GetString("LabelLevelSolvedTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Moves: {0}.
        '''</summary>
        Friend Shared ReadOnly Property LabelMovesFormat() As String
            Get
                Return ResourceManager.GetString("LabelMovesFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Pushes: {0}.
        '''</summary>
        Friend Shared ReadOnly Property LabelPushesFormat() As String
            Get
                Return ResourceManager.GetString("LabelPushesFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Skin.
        '''</summary>
        Friend Shared ReadOnly Property LabelSkin() As String
            Get
                Return ResourceManager.GetString("LabelSkin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Cheese.
        '''</summary>
        Friend Shared ReadOnly Property LabelSkinCheese() As String
            Get
                Return ResourceManager.GetString("LabelSkinCheese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Export.
        '''</summary>
        Friend Shared ReadOnly Property LabelSkinExport() As String
            Get
                Return ResourceManager.GetString("LabelSkinExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Skrzynki.
        '''</summary>
        Friend Shared ReadOnly Property LabelSkinOriginal() As String
            Get
                Return ResourceManager.GetString("LabelSkinOriginal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Solution length: {0}.
        '''</summary>
        Friend Shared ReadOnly Property LabelSolutionLengthFormat() As String
            Get
                Return ResourceManager.GetString("LabelSolutionLengthFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu for Windows.
        '''</summary>
        Friend Shared ReadOnly Property LabelSplashOS() As String
            Get
                Return ResourceManager.GetString("LabelSplashOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Version: {0}.
        '''</summary>
        Friend Shared ReadOnly Property LabelSplashVersionFormat() As String
            Get
                Return ResourceManager.GetString("LabelSplashVersionFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Stats and options.
        '''</summary>
        Friend Shared ReadOnly Property LabelStats() As String
            Get
                Return ResourceManager.GetString("LabelStats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Hiding behind the Boxes....
        '''</summary>
        Friend Shared ReadOnly Property LabelTrayDescription() As String
            Get
                Return ResourceManager.GetString("LabelTrayDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Click the icon to bring the game back..
        '''</summary>
        Friend Shared ReadOnly Property LabelTrayHint() As String
            Get
                Return ResourceManager.GetString("LabelTrayHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Classic Skrzynki.
        '''</summary>
        Friend Shared ReadOnly Property LevelSetClassic() As String
            Get
                Return ResourceManager.GetString("LevelSetClassic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu XS Extra Difficult.
        '''</summary>
        Friend Shared ReadOnly Property LevelSetXS() As String
            Get
                Return ResourceManager.GetString("LevelSetXS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu About.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemAbout() As String
            Get
                Return ResourceManager.GetString("MenuitemAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Pic&amp;k a color....
        '''</summary>
        Friend Shared ReadOnly Property MenuitemColor() As String
            Get
                Return ResourceManager.GetString("MenuitemColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Confirm level restarts.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemConfirmRestarts() As String
            Get
                Return ResourceManager.GetString("MenuitemConfirmRestarts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Game.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemGame() As String
            Get
                Return ResourceManager.GetString("MenuitemGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Hel&amp;p.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemHelp() As String
            Get
                Return ResourceManager.GetString("MenuitemHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Index.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemHelpTopics() As String
            Get
                Return ResourceManager.GetString("MenuitemHelpTopics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Hide.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemHide() As String
            Get
                Return ResourceManager.GetString("MenuitemHide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu O&amp;pen level file....
        '''</summary>
        Friend Shared ReadOnly Property MenuitemOpenLevelFile() As String
            Get
                Return ResourceManager.GetString("MenuitemOpenLevelFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Stats and options.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemOptions() As String
            Get
                Return ResourceManager.GetString("MenuitemOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Quit.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemQuit() As String
            Get
                Return ResourceManager.GetString("MenuitemQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Re&amp;fresh.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemRefresh() As String
            Get
                Return ResourceManager.GetString("MenuitemRefresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Restart Level....
        '''</summary>
        Friend Shared ReadOnly Property MenuitemRestart() As String
            Get
                Return ResourceManager.GetString("MenuitemRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu S&amp;elect Level....
        '''</summary>
        Friend Shared ReadOnly Property MenuitemSelectLevel() As String
            Get
                Return ResourceManager.GetString("MenuitemSelectLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Level&amp;set.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemSelectLevelSet() As String
            Get
                Return ResourceManager.GetString("MenuitemSelectLevelSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Tools.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemTools() As String
            Get
                Return ResourceManager.GetString("MenuitemTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Undo.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemUndo() As String
            Get
                Return ResourceManager.GetString("MenuitemUndo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Vie&amp;w.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemView() As String
            Get
                Return ResourceManager.GetString("MenuitemView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu .
        '''</summary>
        Friend Shared ReadOnly Property MenuitemWebsite() As String
            Get
                Return ResourceManager.GetString("MenuitemWebsite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to restart this level?.
        '''</summary>
        Friend Shared ReadOnly Property QueryRestartLevel() As String
            Get
                Return ResourceManager.GetString("QueryRestartLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Show.
        '''</summary>
        Friend Shared ReadOnly Property TrayMenuShow() As String
            Get
                Return ResourceManager.GetString("TrayMenuShow", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
