'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LocalizableStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Skrzynki.LocalizableStrings", GetType(LocalizableStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flawless victory: you managed to complete this levelset!.
        '''</summary>
        Friend Shared ReadOnly Property AlertAllLevelsSolved() As String
            Get
                Return ResourceManager.GetString("AlertAllLevelsSolved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no such level.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelDoesNotExist() As String
            Get
                Return ResourceManager.GetString("AlertLevelDoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level file is empty or corrupt.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelEmptyOrBad() As String
            Get
                Return ResourceManager.GetString("AlertLevelEmptyOrBad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while loading level.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelLoadFailure() As String
            Get
                Return ResourceManager.GetString("AlertLevelLoadFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You haven&apos;t reached that far yet.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelNotReachedYet() As String
            Get
                Return ResourceManager.GetString("AlertLevelNotReachedYet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error at reading file.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelsetLoadFailure() As String
            Get
                Return ResourceManager.GetString("AlertLevelsetLoadFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Glorious!.
        '''</summary>
        Friend Shared ReadOnly Property AlertLevelSolved() As String
            Get
                Return ResourceManager.GetString("AlertLevelSolved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not a number.
        '''</summary>
        Friend Shared ReadOnly Property AlertNotANumber() As String
            Get
                Return ResourceManager.GetString("AlertNotANumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skrzynki level files (*.box)|*.box|Sokoban levelsets (*.sok)|*.sok.
        '''</summary>
        Friend Shared ReadOnly Property DialogFileFilter() As String
            Get
                Return ResourceManager.GetString("DialogFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open level file.
        '''</summary>
        Friend Shared ReadOnly Property DialogOpenLevelFile() As String
            Get
                Return ResourceManager.GetString("DialogOpenLevelFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select level:.
        '''</summary>
        Friend Shared ReadOnly Property DialogSelectLevel() As String
            Get
                Return ResourceManager.GetString("DialogSelectLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boxes: Skrzynki.
        '''</summary>
        Friend Shared ReadOnly Property GameName() As String
            Get
                Return ResourceManager.GetString("GameName", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {0} ({1}): #{2}.
        '''</summary>
        Friend Shared ReadOnly Property GameTitleFormat() As String
            Get
                Return ResourceManager.GetString("GameTitleFormat", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Start levelsets at the furthest level reached.
        '''</summary>
        Friend Shared ReadOnly Property CheckBoxBeginFromArrivedLevel() As String
            Get
                Return ResourceManager.GetString("CheckBoxBeginFromArrivedLevel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LabelAboutForWindows() As String
            Get
                Return ResourceManager.GetString("LabelAboutForWindows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LabelAboutInfo() As String
            Get
                Return ResourceManager.GetString("LabelAboutInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LabelAboutLicenceBlurb() As String
            Get
                Return ResourceManager.GetString("LabelAboutLicenceBlurb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LabelAboutVersion() As String
            Get
                Return ResourceManager.GetString("LabelAboutVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reached level:.
        '''</summary>
        Friend Shared ReadOnly Property LabelAchievedLevel() As String
            Get
                Return ResourceManager.GetString("LabelAchievedLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skrzynki:.
        '''</summary>
        Friend Shared ReadOnly Property LabelBoxes() As String
            Get
                Return ResourceManager.GetString("LabelBoxes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Background color:.
        '''</summary>
        Friend Shared ReadOnly Property LabelColor() As String
            Get
                Return ResourceManager.GetString("LabelColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Levelset:.
        '''</summary>
        Friend Shared ReadOnly Property LabelLevelSet() As String
            Get
                Return ResourceManager.GetString("LabelLevelSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moves:.
        '''</summary>
        Friend Shared ReadOnly Property LabelMoves() As String
            Get
                Return ResourceManager.GetString("LabelMoves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LabelOptions() As String
            Get
                Return ResourceManager.GetString("LabelOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pushes:.
        '''</summary>
        Friend Shared ReadOnly Property LabelPushes() As String
            Get
                Return ResourceManager.GetString("LabelPushes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - #.
        '''</summary>
        Friend Shared ReadOnly Property LabelShortPauseAndNumberID() As String
            Get
                Return ResourceManager.GetString("LabelShortPauseAndNumberID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skin.
        '''</summary>
        Friend Shared ReadOnly Property LabelSkin() As String
            Get
                Return ResourceManager.GetString("LabelSkin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cheese.
        '''</summary>
        Friend Shared ReadOnly Property LabelSkinCheese() As String
            Get
                Return ResourceManager.GetString("LabelSkinCheese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export.
        '''</summary>
        Friend Shared ReadOnly Property LabelSkinExport() As String
            Get
                Return ResourceManager.GetString("LabelSkinExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skrzynki.
        '''</summary>
        Friend Shared ReadOnly Property LabelSkinOriginal() As String
            Get
                Return ResourceManager.GetString("LabelSkinOriginal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to for Windows.
        '''</summary>
        Friend Shared ReadOnly Property LabelSplashOS() As String
            Get
                Return ResourceManager.GetString("LabelSplashOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version: .
        '''</summary>
        Friend Shared ReadOnly Property LabelSplashVersionName() As String
            Get
                Return ResourceManager.GetString("LabelSplashVersionName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stats and options.
        '''</summary>
        Friend Shared ReadOnly Property LabelStats() As String
            Get
                Return ResourceManager.GetString("LabelStats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hiding behind the Boxes....
        '''</summary>
        Friend Shared ReadOnly Property LabelTrayDescription() As String
            Get
                Return ResourceManager.GetString("LabelTrayDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Classic Skrzynki.
        '''</summary>
        Friend Shared ReadOnly Property LevelSetClassic() As String
            Get
                Return ResourceManager.GetString("LevelSetClassic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LevelSetSasquatch01() As String
            Get
                Return ResourceManager.GetString("LevelSetSasquatch01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XS Extra Difficult.
        '''</summary>
        Friend Shared ReadOnly Property LevelSetXS() As String
            Get
                Return ResourceManager.GetString("LevelSetXS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemAbout() As String
            Get
                Return ResourceManager.GetString("MenuitemAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pic&amp;k a color....
        '''</summary>
        Friend Shared ReadOnly Property MenuitemColor() As String
            Get
                Return ResourceManager.GetString("MenuitemColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Confirm level restarts.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemConfirmRestarts() As String
            Get
                Return ResourceManager.GetString("MenuitemConfirmRestarts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Game.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemGame() As String
            Get
                Return ResourceManager.GetString("MenuitemGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hel&amp;p.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemHelp() As String
            Get
                Return ResourceManager.GetString("MenuitemHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Index.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemHelpTopics() As String
            Get
                Return ResourceManager.GetString("MenuitemHelpTopics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Hide.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemHide() As String
            Get
                Return ResourceManager.GetString("MenuitemHide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;New game.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemNewGame() As String
            Get
                Return ResourceManager.GetString("MenuitemNewGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O&amp;pen level file....
        '''</summary>
        Friend Shared ReadOnly Property MenuitemOpenLevelFile() As String
            Get
                Return ResourceManager.GetString("MenuitemOpenLevelFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Stats and options.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemOptions() As String
            Get
                Return ResourceManager.GetString("MenuitemOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Quit.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemQuit() As String
            Get
                Return ResourceManager.GetString("MenuitemQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re&amp;fresh.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemRefresh() As String
            Get
                Return ResourceManager.GetString("MenuitemRefresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Restart Level....
        '''</summary>
        Friend Shared ReadOnly Property MenuitemRestart() As String
            Get
                Return ResourceManager.GetString("MenuitemRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to S&amp;elect Level....
        '''</summary>
        Friend Shared ReadOnly Property MenuitemSelectLevel() As String
            Get
                Return ResourceManager.GetString("MenuitemSelectLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level&amp;set.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemSelectLevelSet() As String
            Get
                Return ResourceManager.GetString("MenuitemSelectLevelSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tools.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemTools() As String
            Get
                Return ResourceManager.GetString("MenuitemTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Undo.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemUndo() As String
            Get
                Return ResourceManager.GetString("MenuitemUndo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vie&amp;w.
        '''</summary>
        Friend Shared ReadOnly Property MenuitemView() As String
            Get
                Return ResourceManager.GetString("MenuitemView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property MenuitemWebsite() As String
            Get
                Return ResourceManager.GetString("MenuitemWebsite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to restart this level?.
        '''</summary>
        Friend Shared ReadOnly Property QueryRestartLevel() As String
            Get
                Return ResourceManager.GetString("QueryRestartLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property QuerySelectLevel() As String
            Get
                Return ResourceManager.GetString("QuerySelectLevel", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
